version: '2.0'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app/code
      - /home/app/code/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
  mongodata:  
    image: mongo
    volumes:
      - /data/db
    command: --break-mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata